IpmiFeaturePkg/IpmiFeaturePkg.dec

Removed all dynamic PCDs and moved to fixed at build.
Dynamic PCDs cannot be used in runtime enabled code.

Moved all PCDs to fixed at build

---

IpmiFeaturePkg/IpmiCoreLibs.dsc.inc
IpmiFeaturePkg/IpmiFeaturePkg.dec
IpmiFeaturePkg/Library/IpmiPlatformLibNull/IpmiPlatformLibNull.c
IpmiFeaturePkg/Library/IpmiWatchdogLib/IpmiWatchdogLib.inf

- Move FRB2 PCDs to dynamic
- Cleanup unused code and PCDs

Improvements to the IPMI watchdog implementation

---

.azurepipelines/Ubuntu-GCC5.yml
.azurepipelines/Windows-VS.yml

- Triggers and schedules will be set in pipeline definitions
- Variable groups are used to centralize common settings
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>

.azurepipelines: Use new Mu DevOps YAML Design

---

IpmiFeaturePkg/Library/IpmiSelLib/IpmiSelLib.c

IpmiSelLib contained two functions without static identifiers, meaning they were available outside of the library.
The two functions are meant to be used internally to the library only.
Added static identifiers to IpmiCompCodeToEfiStatus and IpmiAddSelEntry

Added static for non-public functions in library

---

IpmiFeaturePkg/Include/IpmiFeature.h
IpmiFeaturePkg/Include/Library/IpmiCommandLib.h
IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnApp.c

IPMI specification calls out reverse GUID format RFC4122 for transmitting data from the Get System Guid and Get Device Guid formats.
Added data structure defining the format, and modified IpmiGetSystemGuid to return that structure instead of an EFI_GUID.

Use RFC4122 foramt for IpmiGetSystemGuid 

---

.github/advanced-issue-labeler.yml
.github/workflows/label-issues/file-paths.yml
.github/workflows/label-issues/regex-pull-requests.yml
IpmiFeaturePkg/BmcAcpiPowerState/BmcAcpiPowerStateSmm.c
IpmiFeaturePkg/BmcAcpiPowerState/BmcAcpiPowerStateSmm.inf
IpmiFeaturePkg/IpmiFeaturePkg.dsc

Add ExitBootService event and S5 SMI handler for updating BMC ACPI power state.
1. Power on SUT.
2. Check if SUT boot into Shell.
3. Change ACPI Power State to S3/D3.
ipmitool -H 10.134.67.13 -U admin -P admin -I lanplus raw 0x6 0x6 0x83 0x83
ipmitool -H 10.134.67.13 -U admin -P admin -I lanplus raw 0x6 0x7
03* 03**
4. Boot into Windows.
5. Check if state has been changed to S0/D0.
ipmitool -H 10.134.67.13 -U admin -P admin -I lanplus raw 0x6 0x7
00* 00**
6. Shutdown SUT.
7. Check if state has been changed to S5/D3.
ipmitool -H 10.134.67.13 -U admin -P admin -I lanplus raw 0x6 0x7
05* 03**
> Note:
> *00h  S0 / G0   working
> *03h  S3        typically equates to …

Updating BMC ACPI power state.

---

.gitignore
IpmiFeaturePkg/IpmiFeaturePkg.dsc

- Fixes the build by adding the security token for X64.
- Adds MU_BASECORE submodule to the .gitignore file
a function in a new library class in …

Fix X64 build & add MU_BASECORE to gitignore

---

IpmiFeaturePkg/Include/Library/IpmiCommandLib.h
IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLib.inf
IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnSensor.c
pip-requirements.txt

Added file IpmiCommandLibNetSensor.c to hold sensor related functions. 
Added functions IpmiSetSensorThreshold and IpmiGetSensorThreshold.
a …

Add Ipmi Sensor commands Set Threshold and Get Threshold. 

---

IpmiFeaturePkg/GenericIpmi/Common/GenericIpmi.c

Moves parameter validation in `IpmiSendCommandInternal()` to the
beginning of the function so (1) it is not redundantly checked in
a retry loop and (2) to catch an invalid condition before executing
other function logic.
Also update `IpmiPrintCommand()` to explicitly check for `CommandData`
being `NULL` since it will currently dereference a null pointer if
that pointer variable is `NULL`.
- **Breaking change** - Will anyone consuming this …

IpmiFeaturePkg/GenericIpmi: Move parameter validation

---

IpmiFeaturePkg/GenericIpmi/Common/IpmiInitialize.c

**Issue:**
Comparison between `Index` of type `UINT8` and `DataSize` of wider
type `UINT32`.
**Description:**
Comparisons between types of different widths in a loop condition can
cause the loop to behave unexpectedly.
**Resolution:**
Make `Index` a `UINT32` so it is the same width as `DataSize`.
- Examples: Add a new library class, move a …

IpmiFeaturePkg/GenericIpmi: Fix CodeQL type comparison issue

---

IpmiFeaturePkg/GenericIpmi/Common/GenericIpmi.c

Removes a variable that will cause unused variable compiler breaks when DEBUG statements are optimized out.
N/A
N/A

Remove variable for debug level causing compiler break

---

IpmiFeaturePkg/IpmiFeaturePkg.ci.yaml

Adds a PrEval entry to all ci.yaml files to enable the new PrEval Policy 5.
- Examples: Unit tests, integration tests, robot tests, ...
- …

ci.yaml: add PrEval entry

---

IpmiFeaturePkg/Include/Library/PlatformPowerRestorePolicyConfigurationLib.h
IpmiFeaturePkg/IpmiFeaturePkg.dec
IpmiFeaturePkg/IpmiFeaturePkg.dsc
IpmiFeaturePkg/IpmiPowerRestorePolicy/IpmiPowerRestorePolicy.c
IpmiFeaturePkg/IpmiPowerRestorePolicy/IpmiPowerRestorePolicy.inf
IpmiFeaturePkg/IpmiPowerRestorePolicy/ReadMe.md
IpmiFeaturePkg/IpmiPowerRestorePolicy/UnitTest/MockApi.c
IpmiFeaturePkg/IpmiPowerRestorePolicy/UnitTest/TestIpmiPowerRestorePolicyHost.c
IpmiFeaturePkg/IpmiPowerRestorePolicy/UnitTest/TestIpmiPowerRestorePolicyHost.inf
IpmiFeaturePkg/Library/PlatformPowerRestorePolicyConfigurationLibNull/PlatformPowerRestorePolicyConfigurationLibNull.c
IpmiFeaturePkg/Library/PlatformPowerRestorePolicyConfigurationLibNull/PlatformPowerRestorePolicyConfigurationLibNull.inf
IpmiFeaturePkg/Test/IpmiFeaturePkgHostTest.dsc

Please ensure you have read the [contribution docs](https://github.com/microsoft/mu/blob/master/CONTRIBUTING.md) prior
to submitting the pull request. In particular,
[pull request guidelines](https://github.com/microsoft/mu/blob/master/CONTRIBUTING.md#pull-request-best-practices).
Implement IpmiPowerRestorePolicy module for configuring Power Restore Policy via IPMI Chassis Command
- Implement IpmiPowerRestorePolicy module for configuring Power Restore Policy via IPMI Chassis Command, it provides a PlatformPowerRestorePolicyConfigurationLib to retrieve platform setting.
- **Tests** - Does …

Implement IpmiPowerRestorePolicy module

---

IpmiFeaturePkg/IpmiCoreLibs.dsc.inc
IpmiFeaturePkg/Library/IpmiBaseLibDxe/IpmiBaseLibDxe.c

Correct the API name in IpmiBaseLibDxe.c and link IpmiBaseLibDxe for UEFI_APPLICATION module type.
- Examples: Unit tests, integration …

Correct the API name in IpmiBaseLibDxe.c and link IpmiBaseLibDxe for UEFI_APPLICATION module type

---

IpmiFeaturePkg/Include/Library/IpmiBaseLib.h
IpmiFeaturePkg/Library/IpmiBaseLibDxe/IpmiBaseLibDxe.c
IpmiFeaturePkg/Library/IpmiBaseLibNull/IpmiBaseLibNull.c
IpmiFeaturePkg/Library/IpmiBaseLibNull/IpmiBaseLibNull.inf
IpmiFeaturePkg/Library/IpmiBaseLibPei/IpmiBaseLibPei.c
IpmiFeaturePkg/Library/IpmiBaseLibSmm/IpmiBaseLibSmm.c
IpmiFeaturePkg/Library/MockIpmi/IpmiBaseLibMock.c

The IpmiBaseLibNull implementation currently restricts its library types and consumes libraries that it does not use. This change cleans up and generalizes the NULL imlementation. 
Local build
N/A

Change IpmiBaseLibNull to BASE library type

---

IpmiFeaturePkg/IpmiFeaturePkg.dsc

MdePkg/MdeLibs.dsc.inc contains the definitions for the new stack cookie libraries.
- Examples: Unit tests, integration tests, robot tests, …

Use New Stack Cookie Library

---

IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c
IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.inf
IpmiFeaturePkg/IpmiFeaturePkg.dsc

Align with DxeGenericIpmi to use PcdIpmiCommandTimeoutSeconds to control IPMI cmd timeout.
- Examples: Unit tests, integration tests, robot …

Align with DxeGenericIpmi to use PcdIpmiCommandTimeoutSeconds

---

IpmiFeaturePkg/Library/IpmiTransportLibSsif/Ssif.c
IpmiFeaturePkg/Test/UnitTest/SsifUnitTest/BmcSmbusLibTest.c

this is to fix multi-part read issue explained in this bug https://github.com/microsoft/mu_feature_ipmi/issues/188
- Examples: Unit tests, …

fix multi-part read for ssif

---

IpmiFeaturePkg/IpmiSmbios/GoogleTest/IpmiSmbiosGoogleTest.cpp
IpmiFeaturePkg/SpmiTable/GoogleTest/SpmiTableGoogleTest.cpp

Updating Mu projects to apply uncrusty formatting for Cpp files, config updated upstream in edk2 https://github.com/tianocore/edk2/pull/4957 .
Config will be updated in mu_basecore https://github.com/microsoft/mu_basecore/pull/609.
in build or boot …

IpmiFeaturePkgPkg: apply cpp uncrustify changes

---

IpmiFeaturePkg/BmcAcpi/BmcSsdt/BmcSsdt.asl

Remove the ACPI device scope link.
Root cause:
If the system LPC device is not "PC00.LPC0", this SSDT is invaild.
It does not need to be put under any device scope, it just need an ASL device in the root path with all the required methods then the IPMI device will be initialized success and show up in device manager.
- Examples: Add a new …

Remove the ACPI device scope link.

---

IpmiFeaturePkg/IpmiFeaturePkg.dsc

An instance of StackCheckLib must be in each DSC to accommodate -fstack-protector and /GS flags.
- Examples: Unit tests, integration tests, …

Add StackCheckLib Instances to Platform DSC Files

---

IpmiFeaturePkg/GenericIpmi/Common/GenericIpmi.h
IpmiFeaturePkg/GenericIpmi/Common/IpmiInitialize.c
IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c
IpmiFeaturePkg/Include/IpmiInterface.h

Removes the quick returns that cause the BMC Status HOB to not be created during failures in PEI. This allows DXE and MM to check the original init attempt status and fail out quickly if needed.
N/A
N/A

Publish BMC Status even on failure from PEI

---

IpmiFeaturePkg/IpmiFeaturePkg.dec
IpmiFeaturePkg/Test/IpmiFeaturePkgHostTest.dsc
IpmiFeaturePkg/Test/Mock/Include/GoogleTest/Library/MockIpmiSelLib.h
IpmiFeaturePkg/Test/Mock/Library/GoogleTest/MockIpmiSelLib/MockIpmiSelLib.cpp
IpmiFeaturePkg/Test/Mock/Library/GoogleTest/MockIpmiSelLib/MockIpmiSelLib.inf

Added mock IpmiSelLib for use in GoogleTests
Added to a GoogleTest and verified functionality
N/A

Added mock IpmiSelLib files

---

IpmiFeaturePkg/GenericIpmi/StandaloneMm/StandaloneMmGenericIpmi.c
IpmiFeaturePkg/GenericIpmi/StandaloneMm/StandaloneMmGenericIpmi.inf
IpmiFeaturePkg/IpmiCoreLibs.dsc.inc
IpmiFeaturePkg/IpmiFeaturePkg.ci.yaml
IpmiFeaturePkg/IpmiFeaturePkg.dsc
IpmiFeaturePkg/Library/IpmiBaseLibMm/IpmiBaseLibMm.c
IpmiFeaturePkg/Library/IpmiBaseLibMm/IpmiBaseLibMm.inf

Implement the StandaloneMmGenericIpmi driver
Verified the build and boot on a simulator
Include the driver in DSC and FDF file

Implement StandaloneMmGenericIpmi driver and IpmiBaseLibMm library

---

IpmiFeaturePkg/Test/IpmiFeaturePkgHostTest.dsc
IpmiFeaturePkg/Test/Mock/Include/GoogleTest/Library/MockIpmiBaseLib.h
IpmiFeaturePkg/Test/Mock/Library/GoogleTest/MockIpmiBaseLib/MockIpmiBaseLib.cpp
IpmiFeaturePkg/Test/Mock/Library/GoogleTest/MockIpmiBaseLib/MockIpmiBaseLib.inf

Added MockIpmiBaseLib
Consumed this mock Lib under GoogleTests and build successful
N/A

Added MockIpmiBaseLib

---

IpmiFeaturePkg/Test/Mock/Include/GoogleTest/Library/MockIpmiCommandLib.h
IpmiFeaturePkg/Test/Mock/Library/GoogleTest/MockIpmiCommandLib/MockIpmiCommandLib.cpp

Add IpmiSetSensorThreshold and IpmiGetSensorThreshold in the MockIpmiCommandLib
Add IpmiSetSensorThreshold and IpmiGetSensorThreshold in the MockIpmiCommandLib
Unit tests component can call these mock functions success
N/A

Add IpmiSetSensorThreshold and IpmiGetSensorThreshold in the MockIpmiCommandLib

---

IpmiFeaturePkg/BmcAcpi/BmcAcpi.c
IpmiFeaturePkg/BmcAcpi/BmcAcpi.inf
IpmiFeaturePkg/BmcAcpi/BmcSsdt/IpmiOprRegions.asi
IpmiFeaturePkg/IpmiFeaturePkg.dec
IpmiFeaturePkg/Library/IpmiTransportLibKcs/KcsBmc.c
IpmiFeaturePkg/Library/IpmiTransportLibKcs/KcsIpmiTransportLib.inf

KCS data and command registers may be decoded as "discontinuous," so a new PCD is added to manage the command register.
For example:
IO 62h/66h as KCS data and command registers.
This modification does not affect the original operation.
If the system declares CA2h/CA3h, make sure the IPMI KCS works as expected.
If your system KCS data and command registers may be decoded as "discontinuous," please refer this:
Example: 
IO 62h/66h as KCS data and command registers.
```ini
gIpmiFeaturePkgTokenSpaceGuid.PcdIpmiIoBaseAddress|0x62|UINT16|0xF0000009
gIpmiFeaturePkgTokenSpaceGuid.PcdIpmiIoCmdRegister|0x66|UINT16|0xF000000A
```
The IPMI device: …

Supports KCS command register declare

---

.pytool/CISettings.py
IpmiFeaturePkg/IpmiFeaturePkg.dsc

Change to using 202502 Branches.
Ran CI build.
No integration necessary.

CI: Change to using 202502 Branches.

---

IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnApp.c

Initialize the GuidResponse variable in IpmiGetSystemUuid to prevent Random Value when using IpmiBaseLibNull
Verified with BIOS build with IpmiBaseLibNull
N/A

Initialize the GuidResponse variable in IpmiGetSystemUuid
